name: venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2023.5.7
  - certifi=2023.5.7
  - ld_impl_linux-64=2.38
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.4
  - libgcc-ng=13.1.0
  - libgfortran-ng=13.1.0
  - libgfortran5=13.1.0
  - liblapack=3.9.0
  - libopenblas=0.3.23
  - libstdcxx-ng=13.1.0
  - llvm-openmp=14.0.6
  - ncurses=6.4
  - numpy=1.21.6
  - openssl=1.1.1u
  - pip=22.3.1
  - pydensecrf=1.0rc3
  - python=3.7.16
  - python_abi=3.7
  - readline=8.2
  - setuptools=65.6.3
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - astor==0.8.1
      - cycler==0.11.0
      - cython==0.29
      - fonttools==4.38.0
      - gast==0.2.2
      - google-pasta==0.2.0
      - grpcio==1.56.0
      - h5py==3.8.0
      - importlib-metadata==6.7.0
      - keras-applications==1.0.8
      - keras-preprocessing==1.1.2
      - kiwisolver==1.4.4
      - markdown==3.4.3
      - markupsafe==2.1.3
      - matplotlib==3.5.3
      - opencv-python==4.8.0.74
      - opt-einsum==3.3.0
      - packaging==23.1
      - pillow==9.5.0
      - protobuf==3.20.0
      - pyparsing==3.1.0
      - python-dateutil==2.8.2
      - six==1.16.0
      - tensorboard==1.15.0
      - tensorflow==1.15.0
      - tensorflow-estimator==1.15.1
      - termcolor==2.3.0
      - tqdm==4.65.0
      - typing-extensions==4.7.1
      - werkzeug==2.2.3
      - wrapt==1.15.0
      - zipp==3.15.0
